name: fitnetic
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.0.1
  curved_navigation_bar: ^0.2.20
  toast: ^0.1.4
  firebase_auth: ^0.11.1+7
  titled_navigation_bar: ^3.0.1
  location: ^2.3.5
  google_maps_flutter: ^0.5.5
  http: ^0.12.0+2
  carousel_slider: ^1.3.0
  flutter_google_places: ^0.2.3
  geocoder: ^0.1.2
  permission_handler: ^3.1.0
  cloud_firestore: ^0.12.6
  audioplayers: ^0.13.0
  animated_text_kit: ^1.3.1
  firebase_messaging: ^5.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/
    - assets/

